### ISSUE TITLE
Transparent Background issue

### ISSUE THREAD

**Issue by deepak-trimantra** [ErikvdVen/php-gif#4]
Hi,

I need to set background transparent. 
to do so in _createImage() of GIFGenerator.php file i made following changes

            case 'png':                
                    $cImage = imagecreatetruecolor( $w, $h );
                    $background = imagecolorallocate( $cImage, 0, 0, 0 );
                    imagecolortransparent( $cImage, $background );
                    imagealphablending( $cImage, false );
                    imagesavealpha( $cImage, true );
                    break;

This creates transparent background image but if text color set to rgb(0,0,0) then it shows completely black image.
![black](https://cloud.githubusercontent.com/assets/20516464/23655983/ad2f3ba8-035d-11e7-8274-2fa386328783.gif)

so i check if rgb(0,0,0) then i change it to rbg(1,1,1) this creates transparent background image with black text but somehome text loses anti-aliasing

![transparent](https://cloud.githubusercontent.com/assets/20516464/23656032/f60e2aaa-035d-11e7-9d38-2deae2134091.gif)

Without Transparent background image looks like this, text are smooth
![normal](https://cloud.githubusercontent.com/assets/20516464/23656059/164e6582-035e-11e7-9a12-a9730fff031a.gif)

So, i need transparent gif image without losing text anti-aliasing. Texts must be smooth.
Can you please provide any solution for these issues?

**Comment by ErikvdVen** [comment]
In the last weeks I haven't had much time, but I expect to be able to look at your question in short notice. If you've already found a solution to your problem, let me know :)

**Comment by al3wb** [comment]
comment this in GIFencoder.php:
$this->COL = ( $GIF_red > -1 && $GIF_grn > -1 && $GIF_blu > -1 ) ?
						( $GIF_red | ( $GIF_grn << 8 ) | ( $GIF_blu << 16 ) ) : -1;

Probably will solve problem

**Comment by ErikvdVen** [comment]
Assuming that al3wb's solution works, because last comment was from last year, I will close this ticket for now. If it does not fix the issue, this ticket can be reopened.

**Comment by fakerybakery** [comment]
This is easier with the improved and updated fork, [phpgif](https://github.com/phpgif/phpgif). You can use the `transparent` attribute.
